### ISSUE TITLE
Sentencepiece installation fails on Python 3.10

### ISSUE THREAD

**Issue by tsharish** [google/sentencepiece#732]
I am trying to install sentencepiece on Python 3.10 running Windows 10 and it fails with the below result. Is sentencepiece supported on Python 3.10? If not, is building and installing from source my only option? Thank you.

```
Collecting sentencepiece
  Downloading sentencepiece-0.1.96.tar.gz (508 kB)
     |████████████████████████████████| 508 kB 6.8 MB/s
Using legacy 'setup.py install' for sentencepiece, since package 'wheel' is not installed.
Installing collected packages: sentencepiece
    Running setup.py install for sentencepiece ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\tshar\sbert_test\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tshar\\AppData\\Local\\Temp\\pip-install-0nhwc364\\sentencepiece_2899733943fc4377892cac88eac47bde\\setup.py'"'"'; __file__='"'"'C:\\Users\\tshar\\AppData\\Local\\Temp\\pip-install-0nhwc364\\sentencepiece_2899733943fc4377892cac88eac47bde\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tshar\AppData\Local\Temp\pip-record-pplq7bpc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\tshar\sbert_test\venv\include\site\python3.10\sentencepiece'
         cwd: C:\Users\tshar\AppData\Local\Temp\pip-install-0nhwc364\sentencepiece_2899733943fc4377892cac88eac47bde\
    Complete output (22 lines):
    C:\Users\tshar\sbert_test\venv\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\sentencepiece
    copying src\sentencepiece/__init__.py -> build\lib.win-amd64-3.10\sentencepiece
    copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
    copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-3.10\sentencepiece
    running build_ext
    building 'sentencepiece._sentencepiece' extension
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\src
    creating build\temp.win-amd64-3.10\Release\src\sentencepiece
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\tshar\sbert_test\venv\include -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-3.10\Release\src/sentencepiece/sentencepiece_wrap.obj /MT /I..\build\root\include
    cl : Command line warning D9025 : overriding '/MD' with '/MT'
    sentencepiece_wrap.cxx
    src/sentencepiece/sentencepiece_wrap.cxx(2809): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\tshar\sbert_test\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tshar\\AppData\\Local\\Temp\\pip-install-0nhwc364\\sentencepiece_2899733943fc4377892cac88eac47bde\\setup.py'"'"'; __file__='"'"'C:\\Users\\tshar\\AppData\\Local\\Temp\\pip-install-0nhwc364\\sentencepiece_2899733943fc4377892cac88eac47bde\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tshar\AppData\Local\Temp\pip-record-pplq7bpc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\tshar\sbert_test\venv\include\site\python3.10\sentencepiece' Check the logs for full command output.
WARNING: You are using pip version 21.2.4; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\Users\tshar\sbert_test\venv\Scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by taku910** [comment]
Not supported yet.

**Comment by tsharish** [comment]
@taku910 thank you for confirming! Any idea when 3.10 will be supported?

**Comment by taku910** [comment]
Fixed. You can download the python3.10 whl package via pip.

**Comment by daskol** [comment]
@taku910 How was this fixed? It seems that wheels are built manually and then uploaded to PyPI.

I use Python 3.10 and need `sentencepiece` v0.1.95. It seems that the native library is not built because of missing `Makefile` in current working directory at `build_bundled.sh`. Consequently, `python setup.py build_ext` fails since `pkg-config` still can't find the native library.

So, the issues is rooted in these lines.
```shell
make -j $(nproc)
make install
```
The issue that use of `make` as well as degree of parallelism are hardcoded while `cmake` can handle it with `CMAKE_GENERATOR` and `CMAKE_BUILD_PARALLEL_LEVEL` as follows
```shell
cmake --build path/to/build/dir
cmake --install path/to/build/dir
```
Could you, please, fill back old releases of `sentencepiece` for Python 3.10? Some libraries like `flair` have strong requirements on `sentencepiece` (see flairNLP/flair#2105 as an example).
